# Generated by the Starpac release workflow.
class Pgpac < Formula
  desc "Go-first PostgreSQL schema packaging CLI"
  homepage "https://github.com/MagnusOpera/starpac"
  version "__VERSION__"

  if OS.mac? && Hardware::CPU.arm?
    url "__DARWIN_URL__"
    sha256 "__DARWIN_SHA__"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "__LINUX_ARM64_URL__"
    sha256 "__LINUX_ARM64_SHA__"
  end

  if OS.linux? && Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "__LINUX_X64_URL__"
    sha256 "__LINUX_X64_SHA__"
  end

  def install
    bin.install "pgpac"
  end

  test do
    system bin/"pgpac", "--version"
  end
end
