name: Update Homebrew Tap

on:
  workflow_call:
    inputs:
      ref: {required: true, type: string}
      version: {required: true, type: string}
      dry-run: {required: false, default: true, type: boolean}
  workflow_dispatch:
    inputs:
      ref: {required: true, type: string}
      version: {required: true, type: string}
      dry-run: {required: false, default: true, type: boolean}

permissions:
  contents: read

jobs:
  update-homebrew-tap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          path: d1pac
      - uses: actions/checkout@v4
        with:
          repository: magnusopera/homebrew-tap
          path: homebrew-tap
          token: ${{ secrets.PAT_HOMEBREW_TAP }}
      - name: Generate formula
        env:
          D1PAC_GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          ./d1pac/.github/scripts/generate-homebrew-tap \
            "${{ inputs.version }}" \
            ./d1pac/.github/scripts/d1pac-formula-template.rb \
            > ./homebrew-tap/Formula/d1pac.rb
      - name: Commit formula
        working-directory: homebrew-tap
        run: |
          git config user.name magnusopera-bot
          git config user.email bot@magnusopera.io
          git add Formula/d1pac.rb
          git diff --cached --quiet || git commit -m "Brew formula update for d1pac version ${{ inputs.version }}"
      - name: Push formula
        if: ${{ !inputs.dry-run }}
        working-directory: homebrew-tap
        run: git push origin HEAD:main
