# Generated by https://github.com/MagnusOpera/d1pac/blob/main/.github/scripts/generate-homebrew-tap
class D1pac < Formula
  desc "Desired-state schema packaging CLI for Cloudflare D1"
  homepage "https://github.com/MagnusOpera/d1pac"
  version "${D1PAC_VERSION}"

  if OS.mac? && Hardware::CPU.arm?
    url "${D1PAC_DARWIN_ARM64_URL}"
    sha256 "${D1PAC_DARWIN_ARM64_SHA256}"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "${D1PAC_LINUX_ARM64_URL}"
    sha256 "${D1PAC_LINUX_ARM64_SHA256}"
  end

  if OS.linux? && Hardware::CPU.intel?
    url "${D1PAC_LINUX_X64_URL}"
    sha256 "${D1PAC_LINUX_X64_SHA256}"
  end

  def install
    bin.install "d1pac"
  end

  test do
    system bin/"d1pac", "--version"
  end
end
