#!/usr/bin/env bash
set -euo pipefail

D1PAC_VERSION="$1"
template_file="$(realpath "$2")"
D1PAC_GH_REPO="${D1PAC_GH_REPO:-MagnusOpera/d1pac}"
export D1PAC_VERSION

cd "$(mktemp -d)"
gh release download --repo "$D1PAC_GH_REPO" "$D1PAC_VERSION" \
  -p "d1pac-${D1PAC_VERSION}-darwin-arm64.zip" \
  -p "d1pac-${D1PAC_VERSION}-linux-x64.zip" \
  -p "d1pac-${D1PAC_VERSION}-linux-arm64.zip"

for target in \
  "darwin arm64 D1PAC_DARWIN_ARM64" \
  "linux x64 D1PAC_LINUX_X64" \
  "linux arm64 D1PAC_LINUX_ARM64"
do
  set -- $target
  asset="d1pac-${D1PAC_VERSION}-$1-$2.zip"
  printf -v "$3_SHA256" '%s' "$(sha256sum "$asset" | cut -f1 -d' ')"
  printf -v "$3_URL" '%s' "https://github.com/${D1PAC_GH_REPO}/releases/download/${D1PAC_VERSION}/${asset}"
  export "$3_SHA256" "$3_URL"
done

envsubst '$D1PAC_VERSION,$D1PAC_DARWIN_ARM64_URL,$D1PAC_DARWIN_ARM64_SHA256,$D1PAC_LINUX_X64_URL,$D1PAC_LINUX_X64_SHA256,$D1PAC_LINUX_ARM64_URL,$D1PAC_LINUX_ARM64_SHA256' < "$template_file"
