# This file was generated by https://github.com/MagnusOpera/pgpac/blob/main/.github/scripts/generate-homebrew-tap
class Pgpac < Formula
  desc "Go-first PostgreSQL schema packaging CLI"
  homepage "https://github.com/MagnusOpera/pgpac"
  version "${PGPAC_VERSION}"

  if OS.mac? && Hardware::CPU.arm?
    url "${PGPAC_DARWIN_ARM64_URL}"
    sha256 "${PGPAC_DARWIN_ARM64_SHA256}"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "${PGPAC_LINUX_ARM64_URL}"
    sha256 "${PGPAC_LINUX_ARM64_SHA256}"
  end

  if OS.linux? && Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "${PGPAC_LINUX_X64_URL}"
    sha256 "${PGPAC_LINUX_X64_SHA256}"
  end

  def install
    bin.install "pgpac"
  end

  test do
    system bin/"pgpac", "--version"
  end
end
